package com.rickyslash.travis.model

object TravelPreferenceDataSource {
    val travelPreferenceData = listOf(
        "fasilitas",
        "pemandangan_alam",
        "gunung",
        "pantai",
        "tumbuhan",
        "ramah_anak",
        "pelayanan",
        "kenyamanan",
        "makanan",
        "lokasi",
        "rekreasi",
        "bersejarah",
        "edukasi",
        "relaksasi",
        "estetik",
        "kuliner",
        "malam_hari",
        "hemat_biaya",
        "kebersihan",
        "halal",
        "pertemuan",
        "mahasiswa",
        "kemah",
        "terbit_matahari",
        "minuman",
        "hiburan",
        "tradisional",
        "rumah",
        "vegetarian",
        "kegiatan_rekreasi",
        "sepeda_motor",
        "makanan_hari",
        "alam_terbuka",
        "pemandangan_luas",
        "tempat_piknik",
        "aktivitas_air",
        "pemandangan_indah",
        "fotogenik",
        "indoor",
        "outdoor"
    )
}